### PR TITLE
MetaGrocer Webpage

### PR DESCRIPTION
**Pull request by TimAdamson21**
This is our initial merge. We have more work to do, but we wanted to merge early just in case github goes down again.

### CODE REVIEW

**Comment by jayfo** [comment]
You're working on `master`, but need to get onto a feature branch before merging. 

I tried to do this for you, but my rebase failed around some conflicts in some of the commits. Because you know everything is in your directory and new, I wouldn't try to truly "fix" this pull. Instead I'd just do a copy-paste, start with a clean `master` from `uwcse440`, create the feature branch, paste your content back in, and re-submit the pull from there.

**Comment by TimAdamson21** [comment]
Can I create a new branch on my forked repo, then create a pull request from there?

**Comment by jayfo** [comment]
Yes, that's exactly what you need to do.

What I don't know is exactly what issues you'll encounter given that you've been committing to your `master` already.  It means your `master` is out of sync with `uwcse440/master`.

Before you try anything, make a copy-paste backup.

But what It think you could do to repair is something like:

    git checkout master
    git checkout -b ourwork
    git reset master uwcse440/master
    git push -f

That will get you onto your master, create a placeholder, reset your master to ours, and then overwrite your master on GitHub.  After that, you should be able to switch to `ourwork` and submit the pull from there.  Or at least that's what I think when typing `git` commands in a browser.

**Comment by TimAdamson21** [comment]
Ok, I just submitted a pull request from our repo's branch.

**Pull request merged**
