### PR TITLE
Uploading files

### PR DESCRIPTION
**Pull request by mstaehely**
Incorporating feedback from Friday section to finalize (?) website

### CODE REVIEW

**Comment by jayfo** [comment]
Does the video not play?  Maybe it references a file you haven't included?

If you video is > 100mb, Github will reject it.  Re-compress with Handbrake.

On the front overview page, try moving the 3d model up higher in the page?

**Comment by mstaehely** [comment]
It is definitely over 100mb, and this had only been tested locally. Thanks for the heads-up; recompressing now. Will attempt to realign the graphics as well.

Sent from Mail for Windows 10

**Comment by mstaehely** [comment]
Just as a heads-up, GitHub is complaining that it’s larger than 25mb, so I’m re-recompressing it until it reaches that size.

Sent from Mail for Windows 10

From: Matthew Staehely
Sent: Sunday, December 10, 2017 10:30 AM
To: uwcse440/web-cse440-au17; uwcse440/web-cse440-au17
Cc: Author
Subject: RE: [uwcse440/web-cse440-au17] Uploading files (#134)

It is definitely over 100mb, and this had only been tested locally. Thanks for the heads-up; recompressing now. Will attempt to realign the graphics as well.

Sent from Mail for Windows 10

**Comment by jayfo** [comment]
The 720 HQ setting in Handbrake generally works well for me.

Even if it complains, you’ll be fine if it accepts it anyways.

**Comment by mstaehely** [comment]
I also did a quick search and found that it seems like only the web interface disallows files of large size. It did issue a warning but I’m used to ignoring those by now 😊

Sent from Mail for Windows 10

**Pull request merged**
