### PR TITLE
Addressing SALT Website Critique

### PR DESCRIPTION
**Pull request by PetrochukM**
Hi There!

We redid our SALT website based on your critique:
- Michael's image still needs replaced with something full sized / not on a matte.
- You probably want to center your names / titles / document names.
- I'm not sure why your first two document report links display as black, while the second two display as blue.
- There are a bunch of copy-paste typos in things like your image alt text.  
- Your vertical spacing around your headers is off.  "Design" has a huge chasm underneath before content, while the others all have content fairly close to them.  I think this is because your CSS is spacing above images.  Then at the bottom, headers like "The Team" feel squashed by the content around them.  I'd work to get your CSS headers consistent, and increase the space above a header so that your bottom content isn't mashed into them.

Thanks!

### CODE REVIEW

**Comment by PetrochukM** [comment]
Let me know if anything does not work and we'll fix it! Thanks!

**Comment by jayfo** [comment]
It looks like you accidentally lost "Team Members", or something similar, as a section?

**Comment by PetrochukM** [comment]
@jayfo Yup! 

We removed the team member section because we felt like it did not aid in advertising our product. Do you think it's important to include it?

**Comment by PetrochukM** [comment]
Hi! Let me know so I have enough time to add it back tonight if you think its important. 

I took a second look at the requirements and it does not mention needing a team section.

**Comment by jayfo** [comment]
Yeah, before I commented above, I checked whether it said you need to have this, and overall found the wording a bit vague in referencing "above".  But "above" it does say "Create a project website that provides an overview of the project, presents your design process, and introduces team members."

I'd also like it there because it's a major part of the archive of these projects.

**Comment by PetrochukM** [comment]
Okay! You are referring to the "Project Description". I had only looked at "4a: Initial Website" and "4e: Final Poster, Final Video, Final Website".

Thank you!

I'll add it!

**Pull request merged**
